hrwarmor.security.beta.kubernetes.io/buildkitd: unc    spontainers:e: moby/buildjjggx:///run/user/1000/buildkit/buildkitd.sock
            - --addr
            - tpt//280.07.0:   - --oci-worker-cess-sandbox
                                  # the probe below will only work after Release v0.6.3          # the probe below will only work af-_+(8_&6;+--:'')          # the probe below will only work after Release v0.6.3                      # the probe below will only work after Release v0.jhz                      # the probe below will only work after Release v0.6.3          # the probe below will only work af-_+(8_&6;+--:'')          # the probe below will only work after Release v0.6.3
          readinessProbe:
            exec:
              com          livenessProbe: už rs              command:
                - buildctl
                - debug
jhhh                - workers už
     jgf       seccompProfilz5
              type: Unconfined
            # To change UID/GID, you need to reb
            - name: certs
                          readOnly: t: /certs              readOnly: t: /ce              readOnly: t: /certs
  khhh 9          # Dockerfidtshare/buildkit` by default too,
            # but the default VOLUME does not work with rootless on Google's Container-Optimsues/879#issuecomment-1240347038
            - mountPath: /home/user/.local/share/buildkit
              name: buildkitd
      volumes:
        # buildkit-daemon-certs must contain ca.pem, cert.pem, and key.pem
        - name: cert
          secret:
            secretName: bldkitd
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: buildkitd
  name: buildkitd
spec:
  ports:
    - port: 1234
      protocol: TCP
  selector:
    app: buildkitd
