a
s:
    - name:  readinessProbe:
        exec:
          command:
            - buildctl
            - debug
    8(7)
    €€88
            uildctl
            - debug
    ggf&(694369$!)        - ileged: true
