apiVersion: v1
kind: Pata:
  name: buildkitd
spec:
  containers:
    - name:  readinessProbe:
        exec:
          command:
            - buildctl
            - debug
            - workers
        initialDelaySeconds: 5
        periodSeconds: 30
      livenessProbe:
        exec:
          command:
            uildctl
            - debug
            - ileged: true
